analyzer:
  strong-mode:
    implicit-casts: false
  errors:
    # Increase the severity of the unused_import hint.
    unused_import: warning
  exclude:
    - test/data/**
linter:
  rules:
    #- annotate_overrides
    - empty_constructor_bodies
    - empty_statements
    #- unawaited_futures
    - unnecessary_brace_in_string_interps
    - valid_regexps
